# Generated by Django 2.2.16 on 2024-11-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='count_likes',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
